services:
  - type: web
    name: chatbot-app
    env: python
    buildCommand: pip install -r requirements.txt && python3 makedb.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --worker-class sync --preload
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: chatbot-disk
      mountPath: /opt/render/project/src
      sizeGB: 10
    healthCheckPath: /
